name: linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linux-test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dotfiles
        run: /bin/bash -c "$(curl -L raw.githubusercontent.com/kazukitash/dotfiles/main/install.sh)"

      - name: Run install
        run: sudo make prepare && sudo make setup
