name: macos

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dotfiles
        run: /bin/bash -c "$(curl -L raw.githubusercontent.com/kazukitash/dotfiles/main/install.sh)"

      - name: Run install
        run: make prepare && make setup
